# Site settings
name: The International Molecular Exchange Consortium
group: IMEx
email: noreply@ebi.ac.uk
domain: //ebiwd.github.io
baseurl: /IMEx-site
permalink: pretty

# Add custom CSS / JS here
# custom_css:
# - "{{site.baseurl}}/static/css/YOUR-CSS-COMPONENTS.css"
# - "{{site.baseurl}}/static/css/ANOTHER-CSS-COMPONENTS.css"
# custom_js:
# - "{{site.baseurl}}/static/js/YOUR-CSS-COMPONENTS.js"
# - "{{site.baseurl}}/static/js/ANOTHER-CSS-COMPONENTS.js"
ga_code: 'UA-XXXXX-X'


# root repo for this project
repo:        "https://github.com/ebiwd/IMEx-site"
source:      .
destination: ./_site
exclude:     [node_modules, .sass-cache, gulpfile.js, package.json, HOWTO.md]
#plugins:     ./_plugins
future:      false
lsi:         false
markdown:    kramdown
highlighter: rouge

# Allow redirects
# https://help.github.com/articles/redirects-on-github-pages/
#gems:
#  - jekyll-redirect-from
